### ISSUE TITLE
Fix dropdown z-index

### ISSUE THREAD

**Issue by valeriosouza** [YanivNadell/Marketplace-Analyzer#1]
![image](https://github.com/YanivNadell/Marketplace-Analyzer/assets/1946271/083e2e3b-5731-45e6-a18c-c8d6c128ce93)

![image](https://github.com/YanivNadell/Marketplace-Analyzer/assets/1946271/35865375-c719-4909-8082-3e30d2047571)

**Comment by YanivNadell** [comment]
This issue is now fixed :)
